class Configs:
    """
    String structure for Bot configurations and other utilities.
    """

    BOT_NAME = "FTC Bot"
    ICON_URL = "https://cdn.discordapp.com/attachments/559265140151943198/574232209658085377/valkyrie.png"
    THUMB_URL = "https://cdn.discordapp.com/attachments/559265140151943198/574245895516848128/valkyrie_thumb.png"
    BOT_VERSION = "1.2 (Badges Beta)"
    PREFIX = "f!"
    DEV_DATE = "February 2019"
    AUTHOR = "Kairos#5362"
    REPO = "Private"
    LANGUAGE = "Python"
    BASE_MONEY = 100
    BASE_LEVEL = 1
    BASE_EXP = 0
    BASE_REP = 0

class ErrorString:
    """
    String structure for error messages and strings.
    """

    ERR_LOAD = "An error occurred upon loading the module `{}`. ERROR | `{}`"
    ERR_UNLOAD = "An error occurred upon unloading the module `{}`. ERROR | `{}`"
    CMD_NOT_EXIST = "The command **{}** doesn't exist."
    ERR_PING = "An error occurred upon calculating uplink speed, try again."
    ERR_NOT_MEMBER = "The user you provided is not a member of this server."
    WRONGFUL_INP = "Wrong argument is passed into the command `{}`, please consult `{}help {}` for more details."
    MISSING_ARGS = "You are missing a required argument, please consult `{}help {}` for more details."
    SRV_ALREADY_IN_DB = "The server is already in the database."
    SRV_NOT_IN_DB = "The server is not yet registered."
    CHANNEL_ALREADY_IN_DB = "The channel is already registered in the database."
    CHANNEL_NOT_IN_DB = "The channel is not yet registered."
    MUTE_ROLE_REG = "❌ | This role is already registered as a mute role."
    LOGS_CHAN_REG = "❌ | This channel is already registered as a logging channel."
    MUTE_ROLE_NOT = "❌ | Please set a mute role for this server before using the mute command."
    MUTE_SELF_NOT = "❌ | You cannot mute yourself."
    NO_LOGS_CHAN = "❌ | No sanction logs channel is set, please set a logging channel."
    USER_NOT_IN_DB = "❌ | User is not registered in the database."
    SPEC_NOT_IN_DB = "❌ | You or the user is not yet registered in the database."
    ABOUT_LIMIT = "❌ | The about section is limited to 140 characters only."
    INSUF_MONEY = "❌ | You have insufficient coins to complete this operation."
    ZERO_GIVE = "❌ | You cannot give coins with those amount."
    COIN_GIVE_SELF = "❌ | You are not stupid enough to give yourself some coins, you're better than that."
    PURGE_TWO = "❌ | You are not stupid enough to give yourself some coins, you're better than that."
    REP_SELF = "❌ | You are not stupid enough to give yourself some reputation, you're better than that."
    ITEM_NOT_EXIST = "❌ | The item does not exist."
    ALREADY_OWNED = "❌ | You already have this item."
    ALREADY_EQUIPPED = "❌ | Item is already equipped."
    ITEM_DONT_OWN = "❌ | You don't own this item."
    NOT_EQUIPPED = "❌ | Item is not equipped."
    USER_IN_DB = "❌ | User already in database."
    UNEQUIP_BG = "❌ | You currently have a background equipped. Please unequip backgrounds before equipping a new one."
    ROLE_SET_ALREADY = "❌ | This role is already the auto voice channel role."
    ROLE_IS_NONE = "❌ | The auto voice channel is not yet set."
    BOT_NO_PERMS = "❌ | The bot doesn't have sufficient permissions to execute this command or operation."
    CMD_COOLDOWN = "🕒 You are on cooldown for **{:.2f} {}**."
    USER_NO_PERMS = "❌ | You don't have sufficient permissions to execute this command or operation."
    SELF_CMD = "❌ | You cannot do this to yourself."
    BET_INSUF = "❌ | Bet must be greater than {}."
    OPTION_ERR = "❌ | The only available options are {}."
    CMD_REG = "❌ | The channel is already registered as a commands channel."
    CMD_NONE = "❌ | The server currently has no commands channel."
    NOT_CRATE = "❌ | Selected item is not a crate."
    NO_KEY = "❌ | You do not own a key to this crate."
    TICKET_DUPLICATE = "❌ | You already submitted a lottery ticket."

class Messages:
    """
    String structure for general messages and string.
    """

    HELP_ACT = "{}, I have redirected the commands and information to your personal inbox."
    HELP_TITLE = "Commands and Information"
    HELP_DESC = "Use `{}help <command>` for a specific information about a command.\nCommand Prefix: `{}`"
    HELP_OPT = "__**Command:**__ `{}`\n\n__**Description:**__\n{}\n\n__**Usage:**__\n`{}`\n\n__**Argument(s):**__\n`{}`"
    ABT_DESC = "Information about the bot."
    PING_STR = "Fetching data..."
    PING_EMJ = ":ping_pong: :ping_pong: :ping_pong:"
    PING_SUCC = ":ping_pong: | Data bounceback took **{:.1f}** ms."
    SERVER_REGISTERED = "The server **{}** is now registered!"
    SERVER_REVOKED = "The server **{}** is now deleted from the database!"
    TOGGLE_LOGGING_ON = "You enabled logging in the server **{}**."
    TOGGLE_LOGGING_OFF = "You disabled logging in the server **{}**."
    TOGGLE_SANCTIONS_ON = "You enabled sanctions logging in the server **{}**."
    TOGGLE_SANCTIONS_OFF = "You disabled sanctions logging in the server **{}**."
    TOGGLE_NRT_ON = "You enabled strict NRT in the server **{}**."
    TOGGLE_NRT_OFF = "You disabled strict NRT in the server **{}**."
    CHANNEL_REGISTERED = "The channel **{}** is now registered!"
    CHANNEL_REVOKED = "The channel **{}** is now deleted from the database!"
    CHANNEL_IS_NSFW = "The channel **{}** is now declared nsfw!"
    CHANNEL_REVOKED_NSFW = "The channel **{}** is now revoked as an nsfw channel!"
    E_VERIFY_TITLE = "Please verify if this is right."
    E_VERIFY_DESC = "Type **{}** to confirm. (Expires in 20 seconds)"
    E_VERIFY_PERSIST = "Setting Persistence To:"
    E_VERIFY_CHANGING = "Changing Persistence Of:"
    E_VERIFY_BEFORE = "Pesistence Value Before:"
    OPERATION_SUCCESSFUL = "🛠 | Operation successful."
    E_CINFO_TITLE = "📝 | Channel Information"
    E_CINFO_DESC = "Shows information about a channel."
    E_CINFO_CHAN = "Channel:"
    E_CINFO_NSFW = "Is_NSFW:"
    E_CINFO_PERSIST = "Persistence:"
    E_CINFO_ID = "Channel ID:"
    MUTE_ROLE_SET = "✅ | You registered {} as a mute role."
    LOGS_CHAN_SET = "✅ | You registered {} as a logging channel."
    MUTED = "🔇 Muted"
    MUTED_DESC = "{} has been muted **indefinitely**."
    MUTED_DESC_DUR = "{} has been muted for **{}**."
    ALREADY_MUTED = "❌ | User is already muted."
    UNMUTED = "{} has been unmuted after **{}**."
    NOT_MUTED = "❌ | User is not muted."
    EM_UNMUTED = "{} has been unmuted."
    TITLE_UNMUTED = "🔊 Unmuted"
    WARN_TITLE = "⚠ Warning"
    WARN_STR = "You have been warned by a moderator."
    WARN_SUCCESS = "You have warned {} and a message is redirected to his/her inbox."
    EXP_TOGGLE = "✅ | You turned on experience gain."
    EXP_TOGGLE_OFF = "❌ | You turned off experience gain."
    INT_TOGGLE = "✅ | You turned on bot interactions."
    INT_TOGGLE_OFF = "❌ | You turned off bot interaction. Ping a moderator to regain your bot interaction permissions."
    REG_WAIT = "📲 | This might take a while... please wait."
    REG_SUCC = "✅ | Success! Appended **{}** users in database."
    REG_CHAN_SUCC = "✅ | Success! Appended **{}** channel(s) in database."
    LOG_WARN = "📝 Warning Given"
    LOG_WARNER = "Warned By:"
    LOG_WARNED = "Warned User:"
    LOG_WARN_REASON = "Reason Given:"
    LOG_WARN_USER_TOT = "User's Accumulated Warnings:"
    LOG_WARN_DESC = "Logs all moderator's warnings"
    NO_USER_REG = "0️⃣ | Nothing is registered."
    NO_CHANNEL_REG = "0️⃣ | Nothing is registered."
    DAILY_RECEIVED = "💵 | You have received your daily `{}` coins!"
    DELETED_MSG = "⚡ | Deleted **{}** messages."
    USER_DELETED_MSG = "⚡ | Deleted **{}** of {}'s messages."
    REP_ADD = "➕ | You gave {} a reputation point!"
    NRT_DESC = "All interrupts will be sanctioned by moderators."
    NRT_TAKE = "{} will be taking over the chat traffic in **{}**."
    NRT_TAKER = "{} will now be taking over the chat traffic.\nAll interruptions will be sanctioned."
    NRT_THIRTY = "No reply thread will start in **thirty seconds**."
    ITEM_INV = "🛍 You successfully bought an item. It is now in your inventory!"
    ITEM_EQUIPPED = "✅ | Item is now equipped."
    ITEM_UNEQUIPPED = "✅ | Item is now unequipped."
    LOOT_SUCCESSFUL = "⚒ | You dig through the logs and messages and found **{}** coins."
    LOOT_FAILURE = "❌ | You found nothing here and lost **{}** coins."
    LOOT_FAIL = "😢 | You found nothing here, not even the void."
    ROLE_SET = "✅ | {} will now be the auto voice channel role."
    ROLE_REMOVE = "✅ | You removed the current auto voice channel role."
    SELL_STR = "✅ | You sold the item and received `{}` coins in return."
    LEVEL_UP = "🆙 | {} has leveled up to **{}**!"
    COIN_WIN = "💲 The coin drew **{}** and you guessed **{}**. You won **{}** coins."
    COIN_LOSE = "💲 The coin drew **{}** and you guessed **{}**. You lost **{}** coins."
    CMD_SUCCESS = "✅ | You successfully set **{}** as a commands channel."
    CMD_REMOVE = "✅ | You successfully removed **{}** as a commands channel."
    GAMBLE_WON = "💯 | You gambled your **{}** coins and you won **{}** coins."
    GAMBLE_LOSE = "😢 | You lost your **{}** coins."
    GAMBLE_LOST_ALL = "😭 | You gambled all of your coins and lost everything."
    CRATE_NONE = "📦 | The crate contains nothing."
    CRATE_WON = "📦 | The crate contains **{}**!"
    LOG_BLOCKED = "✅ | **{}** is now blocked for logging."
    LOG_UNBLOCKED = "✅ | **{}** is now unblocked for logging"

class Themes:
    """
    Structure for bot's aesthetics and themes.
    """

    MAIN_COL = 0x7289DA
